feat[ci-yaml]: Add openshift platform to mdap ci for v1.0.x branch
openebs/zfs pull request #242
Opened 2019-06-04 10:18 UTC by nsathyaseelan

Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>

- Updated gitlab ci yaml to  Enable e2e pipelines to run on openshift.

2019-06-04 10:24 UTC, vishnuitta commented
@nsathyaseelan there are changes in the way repos are made. You need to look at .travis.yml of the v1.0.x branch https://github.com/openebs/cstor/blob/v1.0.x/.travis.yml.. check for libcstor.git

2019-06-04 11:45 UTC, vishnuitta requested changes
Request changes as per the comments provided

2019-06-05 04:44 UTC, mynktl approved these changes

2019-06-05 04:51 UTC, vishnuitta approved these changes
changes are good

2019-06-05 08:25 UTC, merged